app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView

urlpatterns = [
                  path(
                      "", RedirectView.as_view(url="/accounts/login", permanent=False), name="index"
                  ),
                  path("admin/", admin.site.urls),
                  path("accounts/", include("django.contrib.auth.urls")),
                  path("preventivas/", include("preventiva.urls")),
                  path("corretivas/", include("corretiva.urls")),
                  path("cameras/", include("cameras.urls")),
                  path("processadores/", include("processadores.urls")),
                  path("acompanhamento/", include("acompanhamento.urls")),
                  path("relatorios/", include("relatorios.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

processadores/urls.py
from django.urls import path
from processadores import views

app_name = 'processadores'

urlpatterns = [
    path('', views.ProcessadorListView.as_view(), name='listar'),
    path('adicionar', views.ProcessadorCreateView.as_view(), name='adicionar'),
    path('atualizar/<pk>', views.ProcessadorUpdateView.as_view(), name='atualizar'),
    path('deletar/<pk>', views.ProcessadorDeleteView.as_view(), name='deletar'),
]

processadores/models.py
from django.db import models

class Processador(models.Model):

    identificacao = models.CharField('Nome', max_length=10)
    serie = models.CharField('Serie', max_length=10, null=False, blank=False)
    numero_processador = models.CharField('Numero Processador', max_length=10)
    faixa = models.IntegerField()
    endereco = models.CharField('Endereco', max_length=250)
    latitude = models.CharField('Latitude', max_length=10)
    longitude = models.CharField('Longitude', max_length=10)
    velocidade = models.CharField('Velocidade', max_length=3)
    municipio = models.CharField('Municipio', max_length=100)
    regional = models.CharField('Regional', max_length=50)
    fabricante = models.CharField('Fabricante', max_length=20)
    cliente = models.CharField('Cliente', max_length=250)
    centro_custo = models.CharField('Centro custo', max_length=100)
    modelo = models.CharField('Modelo', max_length=100)
    tipo = models.CharField('Tipo', max_length=100)



    class Meta:
        verbose_name = "Processador"
        verbose_name_plural = "Processadores"
        ordering = ["-identificacao"]


    def __str__(self):
        return f"{self.identificacao} - {self.cliente}"

processadores/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from processadores.models import Processador


# Create your views here.
class ProcessadorListView(LoginRequiredMixin, ListView):
    template_name = "processador/processador_list.html"
    model = Processador

    def get_context_data(self, **kwargs):
        context = super(ProcessadorListView, self).get_context_data(**kwargs)
        context['qtd_processadores'] = Processador.objects.all().count()
        return context


class ProcessadorCreateView(LoginRequiredMixin, CreateView):
    template_name = "processador/processador_create.html"
    template_name_suffix = "_create"
    model = Processador
    fields = "__all__"
    success_url = reverse_lazy("processadores:listar")

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(reverse_lazy("processadores:listar"))


class ProcessadorUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "processador/processador_update.html"
    template_name_suffix = "_update"
    model = Processador
    fields = "__all__"


class ProcessadorDeleteView(DeleteView):
    template_name = 'processador/processador_confirm_delete.html'
    model = Processador
    queryset = Processador.objects.all()
    success_url = reverse_lazy("processadores:listar")

processadores/templates/processadores/processadores_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<div class="container-content expandido" id="conteudo">
    <h2>
    Tem certeza que deseja apagar o processador '{{object.identificacao}}?
    </h2>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Sim, tenho certeza" class="sucesso"/>
        <input class="problema" type="reset" value="Não quero apagar mais"
               onClick="history.back()" />
    </form>
</div>


{% endblock content %}

processadores/templates/processadores/processadores_create.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="row mt-1">
        <div class="col">
            <div class="principal">
                <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_form_errors form %}
                {% bootstrap_button button_type="submit" button_class="btn-primary" size="sm" content="Enviar" %}
				{% bootstrap_button button_type="reset" button_class="btn-danger" size="sm" content="Cancelar" %}
				{% bootstrap_button button_type="link" href="/preventivas" button_class="btn-warning" size="sm" content="Retornar" %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

processadores/templates/processadores/processadores_list.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="row m-2">
    <div class="col">
        {% bootstrap_button "Adicionar" button_type="link" size="sm" href="./adicionar"  %}
    </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="principal table-responsive">
                <table class="table text-nowrap table-bordered">
                    <thead>
                    <tr>
                        <th colspan="14">Quantidade de processadores: {{ qtd_processadores }}</th>
                    </tr>
                    <tr>
                        <th scope="col">Ações</th>
                        <th scope="col">Identificação</th>
                        <th scope="col">Série</th>
                        <th scope="col">Número Processador</th>
                        <th scope="col">Faixa</th>
                        <th scope="col">Endereço</th>
                        <th scope="col">Município</th>
                        <th scope="col">Regional</th>
                        <th scope="col">Fabricante</th>
                        <th scope="col">Cliente</th>
                        <th scope="col">Centro de Custo</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Tipo</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for p in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'processadores:atualizar' pk=p.id %}" class="btn btn-outline-primary btn-sm"><i class="bi bi-pen-fill"></i></a>
                                |
                                 <a href="{% url 'processadores:deletar' pk=p.id %}" class="btn btn-outline-danger btn-sm"><i class="bi bi-trash-fill"></i></a>
                            </td>
                            <td>{{ p.identificacao }}</td>
                            <td>{{ p.serie }}</td>
                            <td>{{ p.numero_processador }}</td>
                            <td>{{ p.faixa }}</td>
                            <td>{{ p.endereco }}</td>
                            <td>{{ p.municipio }}</td>
                            <td>{{ p.regional }}</td>
                            <td>{{ p.fabricante }}</td>
                            <td>{{ p.cliente }}</td>
                            <td>{{ p.centro_custo }}</td>
                            <td>{{ p.modelo }}</td>
                            <td>{{ p.tipo }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <nav class="nav">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                                <li class="page-item"><a class="page-link"
                                                         href="?page={{ page_obj.previous_page_number }}">previous</a>
                                </li>
                            {% endif %}
                            <li class="page-item page-link">Page {{ page_obj.number }}
                                of {{ page_obj.paginator.num_pages }}.
                                {% if page_obj.has_next %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page_obj.next_page_number }}">next</a>
                                    </li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page_obj.paginator.num_pages }}">last
                                        &raquo;</a></li>
                                {% endif %}
                        </ul>
                        </span>
                    </nav>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

processadores/templates/processadores/processadores_update.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="row mt-1">
        <div class="col">
            <div class="principal">
                <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_form_errors form %}
                {% bootstrap_button button_type="submit" button_class="btn-primary" size="sm" content="Enviar" %}
				{% bootstrap_button button_type="reset" button_class="btn-danger" size="sm" content="Cancelar" %}
				{% bootstrap_button button_type="link" href="/preventivas" button_class="btn-warning" size="sm" content="Retornar" %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}