app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView

urlpatterns = [
                  path(
                      "", RedirectView.as_view(url="/accounts/login", permanent=False), name="index"
                  ),
                  path("admin/", admin.site.urls),
                  path("accounts/", include("django.contrib.auth.urls")),
                  path("preventivas/", include("preventiva.urls")),
                  path("corretivas/", include("corretiva.urls")),
                  path("cameras/", include("cameras.urls")),
                  path("processadores/", include("processadores.urls")),
                  path("acompanhamento/", include("acompanhamento.urls")),
                  path("relatorios/", include("relatorios.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cameras/urls.py
from django.urls import path
from .views import *

app_name = "cameras"

urlpatterns = [
    path("", CameraListView.as_view(), name="list"),
    path("cadastro", CameraCreateView.as_view(), name="create"),
    path("atualizar/<int:pk>", CameraUpdateView.as_view(), name="update"),
    path("excluir/<int:pk>", CameraDelete.as_view(), name="delete"),
]

cameras/models.py
from django.db import models


class Cameras(models.Model):
    ponto = models.CharField(max_length=6)
    regiao = models.CharField(max_length=50)
    nome_ponto = models.CharField(max_length=100)
    ip = models.GenericIPAddressField()
    nome_camera = models.CharField(unique=True, max_length=150)
    firmware = models.CharField(max_length=50, blank=True, null=True)
    serial = models.CharField(max_length=50, blank=True, null=True)
    porta = models.CharField(max_length=6)
    modelo = models.CharField(max_length=150, blank=True, null=True)
    longitude = models.CharField(max_length=10, blank=True, null=True)
    latitude = models.CharField(max_length=10, blank=True, null=True)
    atualizado = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "cameras"
        ordering = ["ponto"]

cameras/forms.py
from django import forms

from cameras.models import Cameras


class CameraForm(forms.ModelForm):
    class Meta:
        model = Cameras
        fields = "__all__"

class CameraFilterForm(forms.Form):
    ponto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),required=False)
    serial = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),required=False)
    regiao = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),required=False)
    nome_camera = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),required=False)

cameras/views.py
from datetime import datetime
from typing import Any
from django.db.models.query import QuerySet
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from .models import Cameras
from .forms import CameraForm, CameraFilterForm


class CameraListView(LoginRequiredMixin, ListView):
    login_url = "/accounts/login/"
    model = Cameras
    paginate_by = 50
    template_name = "camera_list"

    def get_queryset(self) -> QuerySet[Any]:
        cameras = super().get_queryset().order_by("ponto","porta")
        ponto = self.request.GET.get("ponto")
        serial = self.request.GET.get("serial")
        regiao = self.request.GET.get("regiao")
        nome_camera = self.request.GET.get("nome_camera")

        if ponto:
            cameras = cameras.filter(ponto__icontains=ponto)
        if serial:
            cameras = cameras.filter(serial__icontains=serial)
        if regiao:
            cameras = cameras.filter(regiao__icontains=regiao)
        if nome_camera:
            cameras = cameras.filter(nome_camera__icontains=nome_camera)

        return cameras

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cameras = self.get_queryset()
        context["qtd_cameras"] = cameras.count()
        context["form"] = CameraFilterForm(self.request.GET or None)
        context["permissoes"] = self.request.user.get_all_permissions()
        return context



class CameraCreateView(LoginRequiredMixin, CreateView):
    login_url = "/accounts/login/"
    model = Cameras
    form_class = CameraForm
    success_url = reverse_lazy("cameras:create")
    template_name_suffix = "_create_form"

    def get_initial(self, *args, **kwargs) -> dict[str, Any]:
        initial = super().get_initial(**kwargs)
        initial["atualizado"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return initial


class CameraUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/accounts/login/"
    model = Cameras
    form_class = CameraForm
    template_name_suffix = "_update_form"

    def get_initial(self, *args, **kwargs) -> dict[str, Any]:
        initial = super().get_initial(**kwargs)
        initial["atualizado"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return initial

    def get_success_url(self):
        """
        Constrói a URL de redirecionamento com parâmetros de filtro.
        """
        camera = self.object
        base_url = reverse('cameras:list')
        query_params = {'ponto': camera.ponto}
        encoded_params = urlencode(query_params)
        redirect_url = f'{base_url}?{encoded_params}'
        return redirect_url


class CameraDelete(LoginRequiredMixin, DeleteView):
    login_url = "/accounts/login/"
    queryset = Cameras.objects.all()
    success_url = reverse_lazy("cameras:list")
    template_name_suffix = "_confirm_delete"

cameras/templates/cameras/cameras_confirm_delete.html
{% extends "base.html" %} {% block content %}
    <div class="row custom_header my-2">
        <div class="col">
            <h1>Confirmar Exclusão!</h1>
        </div>
    </div>
    <div class="row principal">
        <div class="col">
            <h2>
                Tem certeza que deseja apagar o termo {{ object.ponto }} - {{ object.porta }}
            </h2>
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" value="Sim, tenho certeza" class="btn bg_primary btn-sm"/>
                <input class="btn bg_danger btn-sm" type="reset" value="Não quero apagar mais"
                       onClick="history.back()"/>
            </form>
        </div>
    </div>

{% endblock content %}

cameras/templates/cameras/cameras_create_form.html
{% extends "base.html" %} {% load static %}{% load django_bootstrap5 %} {% block content %}
    <div class="row custom_header m-2">
        <div class="col">
            <h3>Formulário de Cadastro de Câmera</h3>
        </div>
    </div>
    <div class="row principal m-2">
        <div class="col">
            <input class="btn bg_warning btn-sm" type="reset" value="Retornar"
                       onClick="history.back()"/>
            <hr>
            <div>{% bootstrap_form_errors form layout='inline' %}</div>
            <form action="" method="post" class="form">
                {% csrf_token %}
                <div class="row mt-2">
                    <div class="col-4">
                        {% bootstrap_field form.ponto label_class="negrito" size=small show_label=True %}
                    </div>
                    <div class="col-4">
                        {% bootstrap_field form.regiao label_class="negrito" size=small show_label=True %}
                    </div>

                    <div class="col-4">
                        {% bootstrap_field form.nome_ponto label_class="negrito" size=small show_label=True %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        {% bootstrap_field form.ip size=small label_class="negrito" show_label=True %}
                    </div>
                    <div class="col-4">
                        {% bootstrap_field form.porta size=small label_class="negrito" show_label=True %}
                    </div>
                    <div class="col-4">
                        {% bootstrap_field form.nome_camera size=small label_class="negrito" show_label=True %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        {% bootstrap_field form.longitude size=small label_class="negrito" show_label=True %}
                    </div>
                    <div class="col-4">
                        {% bootstrap_field form.latitude size=small label_class="negrito" show_label=True %}
                    </div>
                </div>
                <div>
                    {% bootstrap_button button_type="submit" content="OK" %}
                    {% bootstrap_button button_type="reset" content="Cancel" %}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

cameras/templates/cameras/cameras_list.html
{% extends "base.html" %} {% load static %} {% load django_bootstrap5 %} {% block content %}
<div class="row custom_header m-2">
    <div class="col">
        <h3>Lista de Câmeras</h3>
    </div>
</div>
<div class="row m-2 principal">
    <div class="col-1">
        <input class="btn bg_warning btn-sm" type="reset" value="Retornar"
               onClick="history.back()"/>
    </div>
    <div class="col-11">
        <form action="">
            <div class="row">
                <div class="col">
                    {% bootstrap_field form.ponto size="sm" show_label='skip' %}
                </div>
                <div class="col">
                    {% bootstrap_field form.serial size="sm" show_label='skip' %}
                </div>
                <div class="col">
                    {% bootstrap_field form.regiao size="sm" show_label='skip' %}
                </div>
                <div class="col">
                    {% bootstrap_field form.nome_camera size="sm" show_label='skip' %}
                </div>
                <div class="col">
                    <button
                            type="submit"
                            class="btn btn-sm bg_primary">
                        Pesquisar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row m-2 principal">
    <div class="col">
        <div class="nav">
            <ul class="pagination">
                <!-- Paginação Anterior -->
                {% if page_obj.has_previous %}
                {% if request.GET.ponto or request.GET.regiao or request.GET.serial or request.GET.nome_camera %}
                <li class="page-item">
                    <a class="page-link"
                       href="?ponto={{ request.GET.ponto }}&regiao={{ request.GET.regiao }}&serial={{ request.GET.serial }}&nome_camera={{ request.GET.nome_camera }}&page=1">&laquo;
                        primeira</a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                       href="?ponto={{ request.GET.ponto }}&regiao={{ request.GET.regiao }}&serial={{ request.GET.serial }}&nome_camera={{ request.GET.nome_camera }}&page={{ page_obj.previous_page_number }}">anterior</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo; primeira</a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                       href="page={{ page_obj.previous_page_number }}">anterior</a>
                </li>
                {% endif %}
                {% endif %}
                <!-- Paginação Range de páginas -->
                <li class="page-item page-link">
                    página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
                </li>

                <!-- Paginação para as próximas páginas -->
                {% if page_obj.has_next %}
                {% if request.GET.ponto or request.GET.regiao or request.GET.serial or request.GET.nome_camera %}
                <li class="page-item">
                    <a class="page-link"
                       href="?ponto={{ request.GET.ponto }}&regiao={{ request.GET.regiao }}&serial={{ request.GET.serial }}&nome_camera={{ request.GET.nome_camera }}&page={{ page_obj.next_page_number }}">próxima</a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                       href="?ponto={{ request.GET.ponto }}&regiao={{ request.GET.regiao }}&serial={{ request.GET.serial }}&nome_camera={{ request.GET.nome_camera }}&page={{ page_obj.paginator.num_pages }}">última
                        &raquo;</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">próxima</a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.paginator.num_pages }}">última
                        &raquo;</a>
                </li>
                {% endif%}

                {% endif %}
            </ul>
        </div>
    </div>
</div>

<div class="row principal  m-2">
    <div class="col table-responsive">

        <table class="table table-sm text-nowrap table-bordered table-striped">
            <thead>
            <tr>
                <th colspan="11" class="table_header_information">Quantidade de câmeras: {{ qtd_cameras }}</th>
            </tr>
            <tr>
                <th scope="col">Ações</th>
                <th scope="col">Ponto</th>
                <th scope="col">Nome do Ponto</th>
                <th scope="col">IP</th>
                <th scope="col">Porta</th>
                <th scope="col">Nome da Câmera</th>
                <th scope="col">Regiao</th>
                <th scope="col">Firmware</th>
                <th scope="col">Serial</th>
                <th scope="col">Modelo</th>
                <th scope="col">Atualizado</th>

            </tr>
            </thead>
            <tbody>
            {% for c in object_list %}
            <tr>

                <td>{% if perms.cameras.change_cameras %}
                    <a class="btn btn-sm btn-outline-info d-inline-block" href="{% url 'cameras:update' pk=c.id %}"
                       target="_blank">
                        <i class="bi bi-pen-fill"></i></a> |
                    {% endif %}
                    {% if perms.cameras.delete_cameras %}
                    <a class="btn btn-sm btn-outline-danger d-inline-block" href="{% url 'cameras:delete' pk=c.id %}"
                       target="_self">
                        <i class="bi bi-eraser-fill"></i></a> |
                    {% endif %}
                    <a class="btn btn-sm btn-outline-success d-inline-block" href="http://{{ c.ip }}:{{ c.porta }}"
                       target="_blank">
                        <i class="bi bi-browser-chrome"></i></a> |
                    <a class="btn btn-sm btn-outline-success d-inline-block" href="http://{{ c.ip }}:9080"
                       target="_blank">
                        <i class="bi bi-arrow-clockwise"></i></a>
                </td>
                <td>{{ c.ponto }}</td>
                <td>{{ c.nome_ponto }}</td>
                <td>{{ c.ip }}</td>
                <td>{{ c.porta }}</td>
                <td>{{ c.nome_camera }}</td>
                <td>{{ c.regiao }}</td>
                <td>{{ c.firmware }}</td>
                <td>{{ c.serial }}</td>
                <td>{{ c.modelo }}</td>
                <td>{{ c.atualizado }}</td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

cameras/templates/cameras/cameras_update_form.html
{% extends "base.html" %} {% load static %}{% load django_bootstrap5 %} {% block content %}
    <div class="row custom_header m-2">
        <div class="col">
            <h3>Formulário de Atualização de Câmera</h3>
        </div>
    </div>
    <div class="row principal m-2">
        <div class="col">
            <input class="btn bg_warning btn-sm" type="reset" value="Retornar"
                       onClick="history.back()"/>
            <hr>
            <div>{% bootstrap_form_errors form layout='inline' %}</div>
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form label_class="negrito"%}
                <div>
                    {% bootstrap_button button_type="submit" content="OK" %}
                </div>
            </form>
        </div>
    </div>

{% endblock %}