acompanhamento/urls.py
from django.urls import path

from acompanhamento import views

app_name = 'acompanhamento'

urlpatterns = [
    path('', views.AcompanhamentoListView.as_view(), name="listar"),
    path('registrar', views.AcompanhamentoCreateView.as_view(), name="registrar"),
    path('atualizar/<pk>', views.AcompanhamentoUpdateView.as_view(), name="atualizar"),
    path('deletar/<pk>', views.AcompanhamentoDeleteView.as_view(), name="deletar"),
    path('detalhe/<pk>', views.AcompanhamentoDetailView.as_view(), name="detalhe"),
    path('exportar', views.AcompanhamentoRelatorioView.as_view(), name="relatorio"),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView

urlpatterns = [
                  path(
                      "", RedirectView.as_view(url="/accounts/login", permanent=False), name="index"
                  ),
                  path("admin/", admin.site.urls),
                  path("accounts/", include("django.contrib.auth.urls")),
                  path("preventivas/", include("preventiva.urls")),
                  path("corretivas/", include("corretiva.urls")),
                  path("cameras/", include("cameras.urls")),
                  path("processadores/", include("processadores.urls")),
                  path("acompanhamento/", include("acompanhamento.urls")),
                  path("relatorios/", include("relatorios.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acompanhamento/models.py
from datetime import datetime

from django.db import models
from django.db.models.functions import ExtractYear, ExtractMonth

from processadores.models import Processador


class Acompanhamento(models.Model):
    id_processador = models.ForeignKey(Processador, on_delete=models.CASCADE, related_name='acompanhamento', verbose_name="Procesador")
    data_inicial = models.DateTimeField("Data Inicial", null=False, blank=False, help_text="Data inicial da ocorrência")
    data_final = models.DateTimeField("Data Final", null=False, blank=False, help_text="Data final da ocorrência")
    problema_apresentado = models.TextField("Problema Apresentado", null=False, blank=False,
                                            help_text="Problema apresentado pelo equipamento")
    acao_tomada = models.TextField("Ação Tomada", null=False, blank=False,
                                   help_text="Ação realizada para retorno do equipamento")
    status_sla = models.CharField('Status do SLA', max_length=10,
                                  choices=[("dentro", "DENTRO DO PRAZO"), ("fora", "FORA DO PRAZO")], default="fora",
                                  help_text="Essa ocorrência durou mais que 1 dia ? se sim, fora do prazo, caso contrário, dentro do prazo.")
    duracao = models.DurationField(editable=False, null=True, blank=True,
                                   help_text="Duração total da ocorrência (calculado automaticamente)")

    class Meta:
        verbose_name = "Acompanhamento"
        verbose_name_plural = "Acompanhamentos"
        ordering = ["data_inicial"]

    def save(self, *args, **kwargs):
        # Verifica se ambas as datas foram definidas para poder calcular a diferença
        if self.data_inicial and self.data_final:
            # Garante que a data final não seja anterior à inicial
            if self.data_final > self.data_inicial:
                self.duracao = self.data_final - self.data_inicial
            else:
                # Opcional: define a duração como zero se as datas forem inválidas
                self.duracao = datetime.timedelta(days=0)

                # Chama o método save() original para salvar o objeto no banco de dados
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.id_processador_id}-{self.id_processador.identificacao}-{self.data_inicial}'

    @classmethod
    def get_anos_disponiveis(cls):
        """
        Retorna uma lista de anos únicos presentes na data_inicial.
        """
        anos = cls.objects.annotate(
            ano=ExtractYear('data_inicial')
        ).values('ano').distinct().order_by('ano')
        return [item['ano'] for item in anos]

    @classmethod
    def get_meses_disponiveis(cls):
        """
        Retorna uma lista de meses únicos presentes na data_inicial.
        """
        meses = cls.objects.annotate(
            mes=ExtractMonth('data_inicial')
        ).values('mes').distinct().order_by('mes')
        return [item['mes'] for item in meses]

acompanhamento/forms.py
from django import forms

from processadores.models import Processador
from .models import Acompanhamento

class AcompanhamentoForm(forms.ModelForm):
    class Meta:
        model = Acompanhamento
        fields = "__all__"
        widgets = {
            'data_inicial': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'data_final': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

class AcompanhamentoFilterForm(forms.Form):
    ANOS_CHOICES = [(ano, str(ano)) for ano in Acompanhamento.get_anos_disponiveis()]
    ANOS_CHOICES.insert(0, ('', 'Todos os Anos'))
    MESES_CHOICES = [(mes, str(mes)) for mes in Acompanhamento.get_meses_disponiveis()]
    MESES_CHOICES.insert(0, ('', 'Todos os Meses'))
    ano = forms.ChoiceField(choices=ANOS_CHOICES, required=False)
    mes = forms.ChoiceField(choices=MESES_CHOICES, required=False)
    processador = forms.ModelChoiceField(queryset=Processador.objects.all(), required=False)

acompanhamento/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView, DetailView

from .forms import AcompanhamentoForm
from .forms import AcompanhamentoFilterForm
from .models import Acompanhamento


class AcompanhamentoListView(LoginRequiredMixin, ListView):
    template_name = "acompanhamento/acompanhamento_list.html"
    model = Acompanhamento

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AcompanhamentoFilterForm(self.request.GET or None)
        return context


    def get_queryset(self):
        instancia = super().get_queryset().all()
        ano = self.request.GET.get('ano')
        mes = self.request.GET.get('mes')
        processador = self.request.GET.get("processador")

        if ano:
            instancia = instancia.filter(data_inicial__year=ano)
        if mes:
            instancia = instancia.filter(data_inicial__month=mes)
        if processador:
            instancia = instancia.filter(id_processador=processador)


        return instancia


class AcompanhamentoCreateView(LoginRequiredMixin, CreateView):
    template_name = "acompanhamento/acompanhamento_form.html"
    template_name_suffix = "_create"
    model = Acompanhamento
    form_class = AcompanhamentoForm
    success_url = reverse_lazy("acompanhamento:listar")

class AcompanhamentoUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "acompanhamento/acompanhamento_form.html"
    template_name_suffix = "_update"
    model = Acompanhamento
    form_class = AcompanhamentoForm
    success_url = reverse_lazy("acompanhamento:listar")


class AcompanhamentoDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'acompanhamento/acompanhamento_confirm_delete.html'
    model = Acompanhamento
    queryset = Acompanhamento.objects.all()
    success_url = reverse_lazy("acompanhamento:listar")


class AcompanhamentoRelatorioView(LoginRequiredMixin, ListView):
    template_name = "acompanhamento/acompanhamento_report.html"
    model = Acompanhamento

    def get_queryset(self):
        instancia = super().get_queryset().all()
        ano = self.request.GET.get('ano')
        mes = self.request.GET.get('mes')
        processador = self.request.GET.get("processador")

        if ano:
            instancia = instancia.filter(data_inicial__year=ano)
        if mes:
            instancia = instancia.filter(data_inicial__month=mes)
        if processador:
            instancia = instancia.filter(id_processador=processador)

        return instancia

class AcompanhamentoDetailView(LoginRequiredMixin, DetailView):
    template_name = "acompanhamento/acompanhamento_detail.html"
    model = Acompanhamento
    queryset = Acompanhamento.objects.all()

acompanhamento/templates/acompanhamento/acompanhamento_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="row custom_header m-2">
        <div class="col">
            <h3>Confirmar de Exclusão!</h3>
        </div>
    </div>
    <div class="row m-2 principal">
        <div class="col">
                <h4>Tem certeza que deseja apagar a ocorrência do {{ object.id_processador.identificacao }} no dia {{ object.data_inicial }}?</h4>
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" value="Sim, tenho certeza" class="btn bg_primary btn-sm"/>
                <input class="btn bg_danger btn-sm" type="reset" value="Não quero apagar mais"
                       onClick="history.back()"/>
            </form>
        </div>
    </div>


{% endblock content %}

acompanhamento/templates/acompanhamento/acompanhamento_detail.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="row custom_header m-2">
        <div class="col">
            <h3>Relatório de Ocorrências</h3>
        </div>
    </div>
    <div class="row principal m-2">
        <div class="col">
            <input class="btn bg_warning btn-sm" type="reset" value="Retornar"
                   onClick="history.back()"/>
        </div>
    </div>
    <div class="row m-2 principal">
        <div class="col">
                <h5>Processador: {{ object.id_processador.identificacao }} -
                    <span>SLA: {{ object.get_status_sla_display }}</span>
                </h5>
                <hr>
                <p><b>Período da Ocorrência:</b> {{ object.data_inicial }} à {{ object.data_final }} -
                    Duração: {{ object.duracao }}
                </p>
                <p><b>Problema Apresentado:</b> <br> {{ object.problema_apresentado }}</p>
                <p><b>Ação Tomada:</b> <br> {{ object.acao_tomada }}</p>
        </div>
    </div>

{% endblock %}

acompanhamento/templates/acompanhamento/acompanhamento_form.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="row custom_header m-2">
        <div class="col">
            <h3>Cadastro de ocorrência</h3>
        </div>
    </div>
    <div class="row principal m-2">
        <div class="col">
            <input class="btn btn-sm bg_warning" type="reset" value="Retornar"
                   onClick="history.back()"/>
            <hr>
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col">
                        {% bootstrap_field form.id_processador show_label="true" size="sm"  %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">{% bootstrap_field form.data_inicial show_label="true" size="sm"  %}</div>
                    <div class="col-4">{% bootstrap_field form.data_final show_label="true" size="sm"  %}</div>
                    <div class="col-4">{% bootstrap_field form.status_sla show_label="true" size="sm"  %}</div>
                </div>
                <div class="row">
                    <div class="col">
                        {% bootstrap_field form.problema_apresentado show_label="true" size="sm"  %}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                         {% bootstrap_field form.acao_tomada show_label="true" size="sm"  %}
                    </div>
                </div>
                {% bootstrap_form_errors form %}
                {% bootstrap_button button_type="submit" button_class="btn btn-sm bg_primary" size="sm" content="Enviar" %}
                {% bootstrap_button button_type="reset" button_class="btn btn-sm bg_warning" size="sm" content="Cancelar" %}
            </form>
        </div>
    </div>
{% endblock %}

acompanhamento/templates/acompanhamento/acompanhamento_list.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="row custom_header m-2">
    <div class="col">
        <h3>Lista de ocorrências com processadores</h3>
    </div>
</div>
<div class="row principal m-2">
    <div class="col-3">
        <input class="btn btn-sm bg_warning" type="reset" value="Retornar"
               onClick="history.back()"/>
        <a href="{% url 'acompanhamento:registrar' %}" class="btn btn-sm bg_primary">Registrar
            Ocorrência</a>
    </div>

    <div class="col-7">
        <form method="get">
            <div class="row">
                <div class="col">
                    {% bootstrap_field form.ano size="sm" show_label='skip' %}
                </div>
                <div class="col">
                    {% bootstrap_field form.mes size="sm" show_label='skip' %}
                </div>
                <div class="col">
                    {% bootstrap_field form.processador size="sm" show_label="skip" %}
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-sm bg_primary">Filtrar</button>
                    <button type="reset" class="btn btn-sm bg_warning">Limpar</button>
                </div>

            </div>
        </form>
    </div>
    <div class="col-1">
        <a href="{% url 'acompanhamento:relatorio' %}?{{ request.GET.urlencode }}" class="btn btn-sm bg_primary">Exportar</a>
    </div>
</div>
<div class="row principal m-2">
    <div class="col table-responsive">
        <nav class="nav">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                       href="?{{ url_parametros }}&page={{ page_obj.previous_page_number }}">Anterior</a>
                </li>
                {% endif %}

                {% for page in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                    <a class="page-link" href="?{{ url_parametros }}&page={{ page }}">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{{ url_parametros }}&page={{ page_obj.next_page_number }}">Próxima</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        <table class="table table-sm text-nowrap table-bordered">
            <thead>
            <tr>
                <th scope="col">Ações</th>
                <th scope="col">Identificação</th>
                <th scope="col">Data Inicial</th>
                <th scope="col">Data Final</th>
                <th scope="col">Problema Apresentado</th>
                <th scope="col">Ação Tomada</th>
                <th scope="col">Status do SLA</th>
                <th scope="col">Duração da Ocorrência</th>
            </tr>
            </thead>
            <tbody>
            {% for a in object_list %}
            <tr>
                <td>
                    <a href="{% url 'acompanhamento:atualizar' pk=a.id %}"
                       class="btn btn-outline-primary btn-sm"><i class="bi bi-pen-fill"></i></a>
                    |
                    <a href="{% url 'acompanhamento:deletar' pk=a.id %}"
                       class="btn btn-outline-danger btn-sm"><i class="bi bi-trash-fill"></i></a>
                    | <a href="{% url 'acompanhamento:detalhe' pk=a.id %}"
                         class="btn btn-outline-warning btn-sm"><i class="bi bi-search"></i></a>
                </td>
                <td>{{ a.id_processador.identificacao }}</td>
                <td>{{ a.data_inicial }}</td>
                <td>{{ a.data_final }}</td>
                <td>{{ a.problema_apresentado|truncatechars:20 }}</td>
                <td>{{ a.acao_tomada|truncatechars:20 }}</td>
                <td>{{ a.get_status_sla_display }}</td>
                <td>{{ a.duracao }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

acompanhamento/templates/acompanhamento/acompanhamento_report.html
{% extends "base_relatorio.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container bg-table">
    <div class="row my-2">
        <div class="col">
            <div class="row">
                <div class="col-1">
                    <img src="{% static 'images/moss.png' %}" class="img-fluid m-1" alt="Logo da Prefeitura de Mossoró">
                </div>
                <div class="col-10 text-center">
                    <h3>Relatório de Ocorrências dos Equipamentos do Contrato SESDEM - MOSSORÓ  </h3>
                </div>
                <div class="col-1">
                    <img src="{% static 'images/logo1.png' %}" class="img-fluid m-1" alt="Logo da Prefeitura de Mossoró">
                </div>
            </div>
            {% for acompanhamento in object_list %}
            <div class="row">
                <div class="col">
                    <table class="table table-bordered bg-table">
                        <thead>
                        <tr>
                            <th>Processador: {{acompanhamento.id_processador.identificacao}} -
                                <span>SLA: {{acompanhamento.get_status_sla_display}}</span></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <b> Período da Ocorrência:</b> {{acompanhamento.data_inicial}} à
                                {{acompanhamento.data_final}} -
                                Duração: {{acompanhamento.duracao}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <b>Problema Apresentado:</b> <br> {{ acompanhamento.problema_apresentado }}</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <b>Ação Tomada:</b> <br> {{ acompanhamento.acao_tomada }}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}