acompanhamento/urls.py
from django.urls import path

from acompanhamento import views

app_name = 'acompanhamento'

urlpatterns = [
    path('', views.AcompanhamentoListView.as_view(), name="listar"),
    path('registrar', views.AcompanhamentoCreateView.as_view(), name="registrar"),
    path('atualizar/<pk>', views.AcompanhamentoUpdateView.as_view(), name="atualizar"),
    path('deletar/<pk>', views.AcompanhamentoDeleteView.as_view(), name="deletar"),
    path('detalhe/<pk>', views.AcompanhamentoDetailView.as_view(), name="detalhe"),
    path('exportar', views.AcompanhamentoRelatorioView.as_view(), name="relatorio"),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView

urlpatterns = [
                  path(
                      "", RedirectView.as_view(url="/accounts/login", permanent=False), name="index"
                  ),
                  path("admin/", admin.site.urls),
                  path("accounts/", include("django.contrib.auth.urls")),
                  path("preventivas/", include("preventiva.urls")),
                  path("corretivas/", include("corretiva.urls")),
                  path("cameras/", include("cameras.urls")),
                  path("processadores/", include("processadores.urls")),
                  path("acompanhamento/", include("acompanhamento.urls")),
                  path("relatorios/", include("relatorios.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cameras/urls.py
from django.urls import path
from .views import *

app_name = "cameras"

urlpatterns = [
    path("", CameraListView.as_view(), name="list"),
    path("cadastro", CameraCreateView.as_view(), name="create"),
    path("atualizar/<int:pk>", CameraUpdateView.as_view(), name="update"),
    path("excluir/<int:pk>", CameraDelete.as_view(), name="delete"),
]

processadores/urls.py
from django.urls import path
from processadores import views

app_name = 'processadores'

urlpatterns = [
    path('', views.ProcessadorListView.as_view(), name='listar'),
    path('adicionar', views.ProcessadorCreateView.as_view(), name='adicionar'),
    path('atualizar/<pk>', views.ProcessadorUpdateView.as_view(), name='atualizar'),
    path('deletar/<pk>', views.ProcessadorDeleteView.as_view(), name='deletar'),
]

relatorios/urls.py
from django.urls import path
from relatorios import views

app_name = 'relatorios'

urlpatterns = [
    path('', views.RelatoriosListView.as_view(), name='listar'),
    path('paineis', views.RelatorioPaineisView.as_view(), name='paineis'),
    path('paineis/ultimas_coletas', views.RelatorioPainelLastData.as_view(), name='ultimas_coletas'),
    path('paineis/exportar', views.ExportListView.as_view(), name='exportar'),
]

app/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load django_bootstrap5 %}
<html lang="pt-BR">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>Extração de Preventivas</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href={% static "styles/base_stprev.css" %}>
</head>
<body>
<main class="container-fluid">
    <div class="row">
        <nav class="navbar navbar-light navbar-expand-lg custom_bg ">
            <div class="container-fluid">
                <a class="navbar-brand px-3" href="#">
                    <img src='{% static "images/logo2.png" %}' alt="Logo Perkons" height="64" width="64"
                         class="d-inline-block align-text-top">
                </a>
                <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href={% url "preventivas" %}>
                            <i class="bi bi-speedometer"></i> Dashboard</a>
                        </li>
                        {# Fim do botão Resumo #}
                        <li class="nav-item dropdown">
                            <a
                                    class="nav-link dropdown-toggle"
                                    href="#"
                                    role="button"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                <i class="bi bi-list-check"></i>
                                Preventiva
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href={% url "preventivas_perkons" %}>Ponto de Coleta</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href={% url "preventivas_velsis" %}>Ponto de Balança</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href={% url "preventivas_salas" %}>Salas de Operação</a>
                                </li>
                            </ul>
                        </li>
                        {# Fim do dropdown preventivas #}
                        <li class="nav-item dropdown">
                            <a
                                    class="nav-link dropdown-toggle"
                                    href="#"
                                    role="button"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                <i class="bi bi-camera-video"></i>
                                Câmeras
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href={% url "cameras:list" %}>Lista de Câmeras</a></li>
                                <li>
                                <li><a class="dropdown-item" href={% url "cameras:create" %}>Cadastro de Câmeras</a>
                                </li>
                            </ul>
                        </li>
                        {# Fim do dropdown Câmeras #}
                        <li class="nav-item dropdown">
                            <a
                                    class="nav-link dropdown-toggle"
                                    href="#"
                                    role="button"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                <i class="bi bi-radar"></i>
                                Processadores
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href={% url "processadores:listar" %}>Lista de
                                    processadores</a></li>
                                <li>
                                <li><a class="dropdown-item" href={% url "acompanhamento:listar" %}>Lista de
                                    acompanhamento</a>
                                </li>
                            </ul>
                        </li>
                        {# Fim do Dropdown Relatórios #}
                        <li class="nav-item dropdown">
                            <a
                                    class="nav-link dropdown-toggle"
                                    href="#"
                                    role="button"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                <i class="bi bi-file-earmark-pdf"></i>
                                Relatórios
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href={% url "relatorios:paineis" %}>Paineis Solares</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex px-3" action="{% url 'logout' %}" method="post" id="logout">
                        {% csrf_token %}
                        <a class="btn bg_primary btn-sm" href="javascript:{}"
                           onclick="document.getElementById('logout').submit();">
                            <span class="link-name"><i class="bi bi-door-open"></i> Sair do Sistema</span>
                        </a>
                    </form>
                </div>
            </div>
        </nav>
    </div>
    <div class="row m-2">
        <div class="col-3 text-center">
             {% if user.is_authenticated %}
                <p class="boas_vindas">Seja bem-vindo, {{ user.get_full_name }}!</p>
            {% endif %}
        </div>
    </div>
    <section>{% block content %}{% endblock content %}</section>
</main>
{% bootstrap_javascript %}
<script src="{% static 'scripts/base.js' %}"></script>
</body>
</html>

app/templates/base_relatorio.html
<!doctype html>
{% load static %}
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
          name="viewport">
    <meta content="ie=edge" http-equiv="X-UA-Compatible">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link href="{% static 'styles/reset_stprev.css' %}" rel="stylesheet">
    <link href="{% static 'styles/relatorio_stprev.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <title>Preventivas </title>
</head>
<body>
{% block content %}
{% endblock %}
<script src="{% static 'scripts/scripts_relatorio.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>

app/templates/resumo.html
{% extends 'base.html' %}{% load static %} {% block content %}
<div class="row justify-content-center">
    <div class="col-11">
        <div class="corpo-conteudo"> <!--CONTAINER GRID-->
            <!--CABEÇALHO PREVENTIVAS-->
            <div class="cabecalho1 custom_header">
                <h3>Preventivas</h3>
            </div>
            <!--PREVENTIVAS-->
            <div class="principal">
                <div class="row justify-content-center">
                    <div class="col">
                        {% if estatistica %}
                        <div class="col d-flex justify-content-center">
                            <div class="spinner-border" role="status" id="spinner">
                                <span class="visually-hidden">Loading...</span>
                            </div>
                        </div>
                        <table class="table table-sm table-bordered" id="tbl_resumo">
                            <thead>
                            <tr>
                                <th colspan="2">Preventivas RMGV / DIVISA</th>
                                <th colspan="2">Preventivas FORA DIVISA</th>
                                <th colspan="2">Total de Preventivas</th>
                            </tr>
                            <tr>
                                <th>Abertas</th>
                                <th>Fechada</th>
                                <th>Abertas</th>
                                <th>Fechadas</th>
                                <th>Chamados Abertos</th>
                                <th>Chamados Fechados</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td id="abertosrmgv"></td>
                                <td id="fechadosrmgv"></td>
                                <td id="abertosforarmgv"></td>
                                <td id="fechadosforarmgv"></td>
                                <td id="abertos"></td>
                                <td id="fechados"></td>
                            </tr>
                            </tbody>
                        </table>
                        {% else %}
                        <h5>Os Chamados de Preventivas não foram abertos</h5>
                        {% endif %}
                    </div>
                </div>
            </div>
            <!--CABEÇALHO CORRETIVAS-->
            <div class="cabecalho2 custom_header">
                <h3>Corretivas</h3>
            </div>

            <!--CORRETIVAS RMGV-->
            <div class="rmgv">
                <h5>RMGV / DIVISA</h5>
                <input
                        type="button"
                        value="Gerar Lista de Corretivas RMGV/DIVISA"
                        class="btn bg_primary btn-sm"
                        onclick='window.location.href="/corretivas/rmgv"'/>
            </div>

            <!--CORRETIVAS FORA RMGV-->
            <div class="fora-rmgv">
                <h5>FORA RMGV</h5>
                <input
                        type="button"
                        value="Gerar Tabela de Corretiva FORA RMGV"
                        class="btn bg_primary btn-sm"
                        onclick='window.location.href="/corretivas/fora_divisa"'/>
            </div>
        </div>
    </div>
    <script src="https://unpkg.com/axios@1.6.7/dist/axios.min.js"></script>
    <script src="{% static 'scripts/resumo.js' %}"></script>
    {% endblock %}